### ISSUE TITLE
关于物品的拾取统计

### ISSUE THREAD

**Issue by zhwblm** [AshuraZero/AddOns#1]
为什么我在中国服务器上不能统计拾取物品 可以弹出编辑价值的框  但是我上传到网站系统的时候却没有任何物品 而且在插件里点击查看物品也是不显示的

**Comment by AshuraZero** [comment]
插件里 查看物品不显示 是由于过滤品质的问题导致的（历史问题）
此问题已经修复在commit 4dba93e93373de9fa5edc27ba0f8d41e198bdd3b

关于上传网站 没有物品问题，需要查看导出的字符串数据

this issue will be closed after 1 week if no further update.

**Comment by zhwblm** [comment]
你好 大神终于回复我了 这个插件适用哪套DKP系统呢 还是以前那套吗 您现在用的有网站系统吗 可以让我看看嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 中午1:49
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] 关于物品的拾取统计 (#1)




插件里 查看物品不显示 是由于过滤品质的问题导致的（历史问题）
 此问题已经修复在commit 4dba93e
 
关于上传网站 没有物品问题，需要查看导出的字符串数据
 
this issue will be closed after 1 week if no further update.

**Comment by AshuraZero** [comment]
适合于原有的WOWDKPER系统(类EQdkp)，并在活动中增加子事件(BOSS)带有分数
DKPRaid 记录导入时选择Boss击杀模式

**Comment by zhwblm** [comment]
我测试过 是不是上传的时候每个BOSS的分还得自己手动输入------------------ 原始邮件 ------------------
发件人: "AshuraZero"<notifications@github.com>
发送时间: 2019年11月29日(星期五) 下午4:20
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com>;
抄送: "zhwblm"<411358827@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AshuraZero/AddOns] 关于物品的拾取统计 (#1)



适合于原有的WOWDKPER系统(类EQdkp)，并在活动中增加子事&#x4EF6;(BOSS)带有分数
 DKPRaid 记录导入时选择Boss击杀模式
 
&mdash;

**Comment by AshuraZero** [comment]
选择BOSS击杀模式会自动填写分数
测试地址：
http://39.104.105.188/dkptest/
admintest:admintest

**Comment by zhwblm** [comment]
那有可能是我这系统的问题吧 我长传每个BOSS的分还得重新输入



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:23
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] 关于物品的拾取统计 (#1)




选择BOSS击杀模式会自动填写分数
 测试地址：
 http://39.104.105.188/dkptest/
 admintest:admintest
 
&mdash;

**Comment by zhwblm** [comment]
您网站系统那套 可否分享呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:23
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] 关于物品的拾取统计 (#1)




选择BOSS击杀模式会自动填写分数
 测试地址：
 http://39.104.105.188/dkptest/
 admintest:admintest
 
&mdash;
