### ISSUE TITLE
Couldn't find inherited node: IEDKPForm

### ISSUE THREAD

**Issue by zhwblm** [AshuraZero/AddOns#2]
一直有报这个错误 你那有这个吗  而且游戏里会提示插件有大量错误

**Comment by AshuraZero** [comment]
感谢测试！
请下载最新版本v20191127
  已知修复：
  1.初始化字体缺失的情况
  2.旧的时间方法
如果还有其他报错请使用[!BaudErrorFrame]收集错误信息等类插件并展示详细截图

**Comment by zhwblm** [comment]
1127还是一样有那个错误 你能给你的merdkp打开的界面截图吗 我感觉跟以前不一样呢 少了点什么 ------------------ 原始邮件 ------------------
发件人: "AshuraZero"<notifications@github.com>
发送时间: 2019年11月29日(星期五) 下午4:14
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com>;
抄送: "zhwblm"<411358827@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AshuraZero/AddOns] Couldn't find inherited node: IEDKPForm (#2)



感谢测试！
 请下载最新版本v20191127
 已知修复：
 1.初始化字体缺失的情况
 2.旧的时间方法
 如果还有其他报错请使用[!BaudErrorFrame]收集错误信息等类插&#x4EF6;并展示详细截图
 
&mdash;

**Comment by AshuraZero** [comment]
禁用所有插件试一试？是否和其他插件冲突了？
Merdkp部分暂时没有完成，请测试CT_RaidTracker部分
***请使用[!BaudErrorFrame]收集错误信息等类插件，并展示详细截图***

**Comment by zhwblm** [comment]
我电脑上就装了这一个插件别的没有&nbsp; 但是还是一直有&nbsp; &nbsp;

11/29 14:56:22.078&nbsp; Loading add-on DKP
11/29 14:56:22.078&nbsp; ** Loading table of contents Interface\AddOns\DKP\DKP.toc
11/29 14:56:22.078&nbsp; ++ Loading file Interface\AddOns\IEDKP\IEDKP.xml
11/29 14:56:22.078&nbsp; Couldn't find inherited node: IEDKPForm
11/29 14:56:22.078&nbsp; Couldn't find inherited node: IEDKPForm







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:31
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] Couldn&#39;t find inherited node: IEDKPForm (#2)




禁用所有插件试一试？是否和其他插件冲突了？
 Merdkp部分暂时没有完成，请测试CT_RaidTracker部分
 请使用[!BaudErrorFrame]收集错误信息等类插件，并展示详细截图
 
&mdash;

**Comment by AshuraZero** [comment]
猜测下列插件冲突
Loading table of contents Interface\AddOns\***DKP\DKP.toc***

**Comment by zhwblm** [comment]
不是这个&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:39
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] Couldn&#39;t find inherited node: IEDKPForm (#2)




猜测下列插件冲突
 Loading table of contents Interface\AddOns*DKP\DKP.toc*
 
&mdash;

**Comment by zhwblm** [comment]
怎么能给WEBDKP的数据迁移过来呢&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:39
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] Couldn&#39;t find inherited node: IEDKPForm (#2)




猜测下列插件冲突
 Loading table of contents Interface\AddOns*DKP\DKP.toc*
 
&mdash;

**Comment by zhwblm** [comment]
你那边没有这么个错误吗&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:39
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] Couldn&#39;t find inherited node: IEDKPForm (#2)




猜测下列插件冲突
 Loading table of contents Interface\AddOns*DKP\DKP.toc*
 
&mdash;

**Comment by AshuraZero** [comment]
> 怎么能给WEBDKP的数据迁移过来呢&nbsp;

请试用迁移小工具
http://39.104.105.188/home/download/LuaDataConversion_20191127_2.zip

**Comment by zhwblm** [comment]
谢谢我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 晚上6:01
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] Couldn&#39;t find inherited node: IEDKPForm (#2)



 
怎么能给WEBDKP的数据迁移过来呢 
  
请试用迁移小工具
 http://39.104.105.188/home/download/LuaDataConversion_20191127_2.zip
 
&mdash;

**Comment by zhwblm** [comment]
咱们的网站DKP系统能分享吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 晚上6:01
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] Couldn&#39;t find inherited node: IEDKPForm (#2)



 
怎么能给WEBDKP的数据迁移过来呢 
  
请试用迁移小工具
 http://39.104.105.188/home/download/LuaDataConversion_20191127_2.zip
 
&mdash;

**Comment by zhwblm** [comment]
您跟国内的IEDKP是一家吗------------------ 原始邮件 ------------------
发件人: "AshuraZero"<notifications@github.com>
发送时间: 2019年11月29日(星期五) 晚上6:01
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com>;
抄送: "zhwblm"<411358827@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AshuraZero/AddOns] Couldn't find inherited node: IEDKPForm (#2)


 
怎么能给WEBDKP的数据迁移过来呢&#xA0;
  
请试用迁移小工具
 http://39.104.105.188/home/download/LuaDataConversion_20191127_2.zip
 
&mdash;
