### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by zhwblm** [AshuraZero/AddOns#3]
![QQ图片20191127205221](https://user-images.githubusercontent.com/45997474/69768087-29237400-11ba-11ea-93a8-b2608b98e224.png)

**Comment by AshuraZero** [comment]
感谢测试！
请下载最新版本v20191127
  已知修复：
  1.初始化字体缺失的情况
  2.旧的时间方法
如果还有其他报错请使用[!BaudErrorFrame]收集错误信息等类插件并展示详细截图
