### ISSUE TITLE
DKP 数据迁移出 错

### ISSUE THREAD

**Issue by zhwblm** [AshuraZero/AddOns#4]
![QQ图片20191130141146](https://user-images.githubusercontent.com/45997474/69897556-a7357580-1388-11ea-9cfd-ee7a68686ded.png)
在解析数据时报错

**Comment by AshuraZero** [comment]
截图信息不在本插件项目范畴之内

**Comment by zhwblm** [comment]
大神可否帮忙解决网站的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AshuraZero"<notifications@github.com&gt;; 
发送时间: 2019年12月2日(星期一) 中午12:18
收件人: "AshuraZero/AddOns"<AddOns@noreply.github.com&gt;; 
抄送: "小鱼"<411358827@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AshuraZero/AddOns] DKP 数据迁移出 错 (#4)




截图信息不在本插件项目范畴之内
 
&mdash;
